### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by niltecedu** [chidimo/voidcoin#1]
Hey so Im new to this thing, I haven't used Django before so I was wondering how do you run this?

Im trying to make a blockchain project using flask and I needed some references on how this works so I can try to implement it in my way.

**Comment by chidimo** [comment]
Okay.
So you have to install django on your local machine. Go to
docs.djangoproject.com and do the first few parts of the tutorial to get up
and running.
To run this project on your local machine... {you should have python 3 and
PostGre SQL installed}
Clone the repo.
Open a cmd and CD into the repo's root i.e. where you have the file
manage.py
Now run "pip install" to install project dependencies.
After that run "python manage.py migrate".
After migration completes, run "python manage.py runserver".
Now view the project in localhost:8000

There's a running version on voidcoin.pythonanywhere.com

Let me know how it goes. But I highly recommend you do the django tutorial
if you have time, at least part 1 of it.

**Comment by niltecedu** [comment]
Hey I have some problems with it, is it because I'm running Django 2.2 instead of 2?
![Screenshot from 2019-04-11 12-25-50](https://user-images.githubusercontent.com/41137440/55936980-71a31700-5c55-11e9-9576-68f794eed09f.png)

**Comment by niltecedu** [comment]
I went through the Django tutorial and we are missing a settings.py but you have a whole folder called settings

**Comment by chidimo** [comment]
Create a file named ".env" at the root of the project and add the below
content


DEBUG=True

DJANGO_SETTINGS_MODULE=voidcoin.settings.dev

SECRET_KEY=-yj%bb6h89%&)&(=%didix35(gaag1&f*$73+=h5b3=v-1uy*p
EMAIL_PORT=587
EMAIL_HOST_PASSWORD=2xF5x0w13ddF

ALLOWED_HOSTS=.localhost

**Comment by niltecedu** [comment]
Its still the same, nvm about it then. I'll make my own using this as a reference. Thanks!

**Comment by chidimo** [comment]
Probably your safest option. Great way to go.
